export const AMENITIES = [
    "Air Condition",
    "Cable TV",
    "Ceiling Height",
    "Fireplace",
    "Disabled Access",
    "Elevator",
    "Fence",
    "Garden",
    "Floor",
    "Furnishing",
    "Garage",
    "Pet Friendly",
    "Heating",
    "Intercom",
    "Parking",
    "WiFi",
    "Renovation",
    "Security",
    "Swimming Pool",
    "Window Type",
    "Search property",
    "Construction Year"
  ] as const;