export const houses = [
  {
    id: 1,
    title: "House in LA",
    city: "Los Angeles",
    district: "Silver Lake",
    street: "456 Sunset Boulevard",
    price: 850000,
    type: "Apartment",
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
    image: [
      "https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=500&q=60",
    ],
    description:
      "Modern California bungalow with stunning views of the Silver Lake Reservoir. Features an open concept living space, updated kitchen with premium appliances, and a spacious backyard perfect for entertaining. Master suite includes a walk-in closet and spa-like bathroom.",
    garage: 2,
    parkingSpace: true,
    pool: true,
    security: true,
    yearBuilt: 1985,
    status: "For Sale",
    amenities: ["Garage", "Pool", "Security System", "Smart Home", "Garden"],
    mapCoordinates: "34.0522° N, 118.2437° W",
    contactNumber: "+1 323 555 0123",
    email: "silverlake@realestate.com",
    agentId: "LA001",
    listingDate: "2024-12-15",
    floor: "2",
    heatingType: "Central",
    AC: true,
    furnished: false,
    petFriendly: true,
    renovation: "Renovated 2022",
  },
  {
    id: 2,
    title: "House in Miami",
    city: "Miami",
    district: "Brickell",
    street: "789 Bay View Drive",
    price: 1200000,
    type: "House",
    bedrooms: 2,
    bathrooms: 2.5,
    area: 150,
    image: [
      "https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&w=500&q=60",
    ],
    description:
      "Luxury waterfront condo in the heart of Brickell. Floor-to-ceiling windows offer breathtaking views of Biscayne Bay. High-end finishes throughout, featuring Italian marble floors and designer kitchen with Sub-Zero appliances.",
    garage: 1,
    parkingSpace: true,
    pool: true,
    security: true,
    yearBuilt: 2019,
    status: "For Sale",
    amenities: ["Swimming Pool", "Gym", "Valet Parking", "24/7 Security", "Spa"],
    mapCoordinates: "25.7617° N, 80.1918° W",
    contactNumber: "+1 305 555 0456",
    email: "brickell@realestate.com",
    agentId: "MIA002",
    listingDate: "2024-11-30",
    floor: "15",
    heatingType: "Heat Pump",
    AC: true,
    furnished: true,
    petFriendly: false,
    renovation: "New Construction",
  },
  {
    id: 3,
    title: "House in Chicago",
    city: "Chicago",
    district: "Lincoln Park",
    street: "321 Willow Street",
    price: 675000,
    type: "House",
    bedrooms: 3,
    bathrooms: 2,
    area: 185,
    image: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=500&q=60",
    ],
    description:
      "Charming brick townhouse in historic Lincoln Park. Features original hardwood floors, exposed brick walls, and a newly renovated kitchen. Private rooftop deck offers stunning skyline views. Steps from parks, shops, and restaurants.",
    garage: 1,
    parkingSpace: true,
    pool: false,
    security: true,
    yearBuilt: 1920,
    status: "For Sale",
    amenities: ["WiFi", "Rooftop Deck", "Fireplace", "Wine Cellar"],
    mapCoordinates: "41.9250° N, 87.6353° W",
    contactNumber: "+1 312 555 0789",
    email: "lincolnpark@realestate.com",
    agentId: "CHI003",
    listingDate: "2024-12-01",
    floor: "3",
    heatingType: "Forced Air",
    AC: true,
    furnished: false,
    petFriendly: true,
    renovation: "Kitchen remodeled 2023",
  },
  {
    id: 4,
    title: "House in Seattle",
    city: "Seattle",
    district: "Queen Anne",
    street: "567 Highland Drive",
    price: 925000,
    type: "House",
    bedrooms: 4,
    bathrooms: 3,
    area: 250,
    image: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=500&q=60",
    ],
    description:
      "Craftsman-style home with panoramic views of Puget Sound and the Olympic Mountains. Featuring a gourmet kitchen, formal dining room, and master suite with private balcony. Finished basement includes home theater and wine cellar.",
    garage: 2,
    parkingSpace: true,
    pool: false,
    security: true,
    yearBuilt: 1925,
    status: "For Sale",
    amenities: ["Air Condition", "Wine Cellar", "Garden", "Smart Home"],
    mapCoordinates: "47.6205° N, 122.3509° W",
    contactNumber: "+1 206 555 0321",
    email: "queenanne@realestate.com",
    agentId: "SEA004",
    listingDate: "2024-12-10",
    floor: "2",
    heatingType: "Radiant",
    AC: false,
    furnished: false,
    petFriendly: true,
    renovation: "Fully restored 2021",
  },
  {
    id: 5,
    title: "House in Austin",
    city: "Austin",
    district: "South Congress",
    street: "890 Music Lane",
    price: 550000,
    type: "House",
    bedrooms: 3,
    bathrooms: 2,
    area: 165,
    image: [
      "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?auto=format&fit=crop&w=500&q=60",
    ],
    description:
      "Trendy modern home in vibrant SoCo district. Open floor plan with polished concrete floors, exposed ductwork, and walls of windows. Chef's kitchen features custom cabinetry and high-end appliances. Spacious deck perfect for outdoor living.",
    garage: 1,
    parkingSpace: true,
    pool: false,
    security: true,
    yearBuilt: 2018,
    status: "For Sale",
    amenities: ["Garage", "Smart Home", "Solar Panels", "EV Charging"],
    mapCoordinates: "30.2672° N, 97.7431° W",
    contactNumber: "+1 512 555 0654",
    email: "soco@realestate.com",
    agentId: "AUS005",
    listingDate: "2024-12-05",
    floor: "2",
    heatingType: "Heat Pump",
    AC: true,
    furnished: false,
    petFriendly: true,
    renovation: "New Construction",
  },
];
